# Generated by Django 4.1.1 on 2023-07-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.user')),
            ],
        ),
    ]
