# Generated by Django 4.1.1 on 2023-07-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0002_entity_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('totalserials', models.IntegerField()),
                ('serialscommissioned', models.IntegerField()),
                ('serialsdecommissioned', models.IntegerField()),
                ('serialspacked', models.IntegerField()),
                ('serialsshipped', models.IntegerField()),
                ('email_duration', models.CharField(max_length=100)),
                ('linked_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.entity_list')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.user')),
            ],
        ),
    ]
