# Generated by Django 4.1.1 on 2023-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serialscommissioned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='serialsdecommissioned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='serialspacked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='serialsshipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalserials',
            field=models.IntegerField(default=0),
        ),
    ]
