# Generated by Django 4.1.1 on 2023-07-25 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0006_alter_product_serialscommissioned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('linked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.product')),
            ],
        ),
        migrations.CreateModel(
            name='serials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_commissioned', models.BooleanField(default=False)),
                ('is_packed', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('linked_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.batch')),
                ('linked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailreport.product')),
            ],
        ),
    ]
