# Generated by Django 4.1.1 on 2023-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0007_batch_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_created_product',
            field=models.BooleanField(default=False),
        ),
    ]
