# Generated by Django 4.1.1 on 2023-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0008_user_is_created_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='is_commissioned',
            field=models.BooleanField(default=True),
        ),
    ]
