# Generated by Django 4.1.1 on 2023-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0009_alter_serials_is_commissioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='is_commissioned',
            field=models.BooleanField(default=False),
        ),
    ]
