# Generated by Django 4.1.1 on 2023-07-31 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0011_user_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serials',
            name='date',
        ),
        migrations.AddField(
            model_name='serials',
            name='commissioned_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='serials',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='serials',
            name='packed_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='serials',
            name='shipped_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
