# Generated by Django 4.1.1 on 2023-08-04 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0013_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_range_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='startenddates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
