# Generated by Django 4.1.1 on 2023-08-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailreport', '0014_alter_report_date_range_report_startenddates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
